### ISSUE TITLE
UI Searchstore

### ISSUE THREAD

**Issue by giusedefabrizio** [lioialessandro/StoreManagerISPW#20]

**Comment by GRonz00** [comment]
Cambio controller

**Comment by lioialessandro** [comment]
Fix full screen

**Comment by lioialessandro** [comment]
ScrollPane usa tutto lo spazio. Fix radius sulla textfield

**Comment by lioialessandro** [comment]
SearchStoreGraphicController ha client e lo passa a StoreGraphicController
