### ISSUE TITLE
UI Shop

### ISSUE THREAD

**Issue by giusedefabrizio** [lioialessandro/StoreManagerISPW#21]

**Comment by lioialessandro** [comment]
Controller

**Comment by lioialessandro** [comment]
Fix full screen
Aggiunto file separato per il prodotto

**Comment by lioialessandro** [comment]
Caricamento automatico dei prodotti dal db

**Comment by lioialessandro** [comment]
Ricerca (solo testo)

**Comment by lioialessandro** [comment]
Fix testo descrizione troppo lungo (la Label ha una width fissa e mostra `...` se il testo è troppo grande; è necessario quindi aggiungere un modo per far leggere tutta la descrizione)

**Comment by lioialessandro** [comment]
StoreGraphicController ha client

**Comment by GRonz00** [comment]
Loyalty card prendeva troppo spazio
